version: '3'

services: 
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL/ROOT_PASSWORD: root
    volumes:
      - mariadb:/var/lib/mysql

  redis:
    image: redis:latest

  frappe:
    build: .
    command: bench start
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
      - redis
    environment:
      SITE_NAME: your-site-name
      DF_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      ADMIN_PASSWORD: admin
      INSTALL_APPS: erpnext,ferum_customs

  frontend:
    image: frappe/frontend
    ports: 
      - "80:80"

volumes: 
  mariadb:
  redis:
